# Generated by Django 2.2.7 on 2019-12-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrels',
            name='Primary_Fur_Color',
            field=models.CharField(choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='Primary Fur Color', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Unique_squirrel_id',
            field=models.CharField(help_text='Unique Squirrel ID', max_length=100, null=True, unique=True),
        ),
    ]
