# Generated by Django 2.2.7 on 2019-12-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrels',
            name='id',
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Unique_squirrel_id',
            field=models.CharField(default=None, help_text='Unique Squirrel ID', max_length=100, primary_key=True, serialize=False),
        ),
    ]
